# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "install requirements"
    command: |
      pip install -U pip
      pip install yapf
      pip install -r requirements.txt
      wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-5.3.1-Linux-x86_64.sh sh Anaconda3-5.3.1-Linux-x86_64.sh -u
      
      

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter
