# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "install requirements"
    command: |
      pip install -U pip
      pip install yapf
      pip install -r requirements.txt
      wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2021.11-Linux-x86_64.sh
      bash Anaconda3-2021.11-Linux-x86_64.sh
      source ~/.bashrc
      conda create -n py37 python=3.7
      source activate py37
      pip install torch==1.3.0
      exit

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter
